In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
#one hot representation

In [6]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[4220, 9454, 4837, 373], [4220, 9454, 4837, 3201], [4220, 4461, 4837, 3896], [7664, 4861, 1183, 8134, 500], [7664, 4861, 1183, 8134, 9297], [1638, 4220, 9943, 4837, 7681], [4482, 7269, 9749, 8134]]


In [8]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4220 9454 4837  373]
 [   0    0    0    0 4220 9454 4837 3201]
 [   0    0    0    0 4220 4461 4837 3896]
 [   0    0    0 7664 4861 1183 8134  500]
 [   0    0    0 7664 4861 1183 8134 9297]
 [   0    0    0 1638 4220 9943 4837 7681]
 [   0    0    0    0 4482 7269 9749 8134]]


In [11]:
dim =10

In [12]:
model =Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

[[[ 0.00845083  0.04185336 -0.03198043 -0.01785064 -0.01729699
   -0.03887375  0.04637386 -0.03284357  0.03390704  0.03809451]
  [ 0.00845083  0.04185336 -0.03198043 -0.01785064 -0.01729699
   -0.03887375  0.04637386 -0.03284357  0.03390704  0.03809451]
  [ 0.00845083  0.04185336 -0.03198043 -0.01785064 -0.01729699
   -0.03887375  0.04637386 -0.03284357  0.03390704  0.03809451]
  [ 0.00845083  0.04185336 -0.03198043 -0.01785064 -0.01729699
   -0.03887375  0.04637386 -0.03284357  0.03390704  0.03809451]
  [-0.02687575  0.00590988 -0.01849876 -0.03325025  0.01278662
    0.03565444 -0.00646105  0.0353096   0.02267534 -0.00804412]
  [ 0.01657085  0.031704    0.03301266 -0.00039167  0.03176722
   -0.04713903 -0.04073911  0.03228411 -0.03405414  0.00508713]
  [ 0.00813435  0.02302327 -0.03295028  0.03146206  0.02962846
   -0.04019911 -0.03882419 -0.04712815 -0.00035445 -0.04481332]
  [-0.01336806  0.00680649  0.02653002 -0.01505908 -0.02800733
   -0.01517788  0.04470904  0.00920821 -0.029645

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 4220, 9454, 4837,  373], dtype=int32)

In [16]:
print(model.predict(embedded_docs)[0])

[[ 0.00845083  0.04185336 -0.03198043 -0.01785064 -0.01729699 -0.03887375
   0.04637386 -0.03284357  0.03390704  0.03809451]
 [ 0.00845083  0.04185336 -0.03198043 -0.01785064 -0.01729699 -0.03887375
   0.04637386 -0.03284357  0.03390704  0.03809451]
 [ 0.00845083  0.04185336 -0.03198043 -0.01785064 -0.01729699 -0.03887375
   0.04637386 -0.03284357  0.03390704  0.03809451]
 [ 0.00845083  0.04185336 -0.03198043 -0.01785064 -0.01729699 -0.03887375
   0.04637386 -0.03284357  0.03390704  0.03809451]
 [-0.02687575  0.00590988 -0.01849876 -0.03325025  0.01278662  0.03565444
  -0.00646105  0.0353096   0.02267534 -0.00804412]
 [ 0.01657085  0.031704    0.03301266 -0.00039167  0.03176722 -0.04713903
  -0.04073911  0.03228411 -0.03405414  0.00508713]
 [ 0.00813435  0.02302327 -0.03295028  0.03146206  0.02962846 -0.04019911
  -0.03882419 -0.04712815 -0.00035445 -0.04481332]
 [-0.01336806  0.00680649  0.02653002 -0.01505908 -0.02800733 -0.01517788
   0.04470904  0.00920821 -0.02964503  0.04738236]]